### ISSUE TITLE
The undead glitch

### ISSUE THREAD

**Issue by rosenbergd** [JayWelsh/coronamap#3] opened 2020-10-06 09:16 UTC
Hi again,

just looking through the other graphs and noticed this:
![image](https://user-images.githubusercontent.com/5484305/95179171-93d11300-07c0-11eb-90c6-51278aa09b81.png)

It seems like the Cumulative Deaths graph has gone down, creepy, but also good news if the lower number is correct (and the higher number is the inaccurate data point)

**Comment by JayWelsh** [comment] 2020-10-06 10:01
Hi @rosenbergd ,

Once again, thank you so much for your feedback, you are amazing.

I have created a pull request to fix the problematic datapoint in the data source here: https://github.com/dsfsi/covid19za/pull/714

I will mark this issue as resolved once the above mentioned PR has been merged.

Thank you so much!

**Comment by JayWelsh** [comment] 2020-10-06 10:24
The fix has been merged and the problem is now resolved.

Thanks @rosenbergd !

**Closed as completed by JayWelsh** 2020-10-06 10:24 UTC
